BookBridge/BookBridge/Views/Login/Find/FindIdView.swift
BookBridge/BookBridge/Views/Login/IdLogin/IdLoginView.swift
BookBridge/BookBridge/Views/Login/IdLogin/IdLoginViewModel.swift
BookBridge/BookBridge/Views/Login/KaKaoLogin/KakaoLoginView.swift
BookBridge/BookBridge/Views/Login/LoginView.swift

- 시작하기 -> 회원가입 화면연결
- 카카오톡 이미지 오타 수정
- 파이어베이스 이메일 로그인 로직 구현

[Feat]: 파이어베이스 이메일 로그인 구현

---

BookBridge/BookBridge.xcodeproj/project.pbxproj
BookBridge/BookBridge/Views/Login/Find/FindIdResultView.swift

[Feat]: 아이디 찾기 결과창

---

BookBridge/BookBridge/ViewModel/BookShelfViewModel.swift
BookBridge/BookBridge/ViewModel/Login/IdLoginViewModel.swift
BookBridge/BookBridge/Views/BookShelf/BookDetailView.swift
BookBridge/BookBridge/Views/BookShelf/BookShelfView.swift
BookBridge/BookBridge/Views/BookShelf/BookView.swift
BookBridge/BookBridge/Views/BookShelf/WishBookAddBtnView.swift
BookBridge/BookBridge/Views/Posting/FindPostingView.swift
BookBridge/BookBridge/Views/SearchBook/SearchBooksView.swift

- 책장View와 도서 검색View의 로직을 변경하였습니다
- 도서 정보View에서 나의 희망 도서버튼을 클릭할경우 추가하는 로직을 추가하였습니다
- 각 책장에 중복으로 들어가는 책들을 removeAll을 사용하여 중복을 제거하였습니다.

[Refactor]: 책장View와 검색View 로직 리팩토링

---

BookBridge/BookBridge.xcodeproj/project.pbxproj
BookBridge/BookBridge/Model/Enum/Location.swift
BookBridge/BookBridge/Utility/Manager/FireStore/FirestoreSignUpManager.swift
BookBridge/BookBridge/Utility/Manager/LocationManager.swift
BookBridge/BookBridge/ViewModel/LocationViewModel.swift
BookBridge/BookBridge/ViewModel/Login/SignUpViewModel.swift
BookBridge/BookBridge/Views/Login/LoginView.swift

Firestore에 User 등록하는 기능 FirestoreSignUpManager에 추가

FirestoreSignUpManager 추가

---

BookBridge/BookBridge.xcworkspace/xcshareddata/swiftpm/Package.resolved
BookBridge/BookBridge/TabBarView.swift
BookBridge/BookBridge/ViewModel/BookShelfViewModel.swift
BookBridge/BookBridge/Views/BookShelf/BookDetailView.swift
BookBridge/BookBridge/Views/BookShelf/BookShelfView.swift
BookBridge/BookBridge/Views/BookShelf/BookView.swift
BookBridge/BookBridge/Views/BookShelf/WishBookAddBtnView.swift

- firebase와 연동하여 책 정보를 추가할수 있게 하였습니다
- 편집 버튼을 넣어 X 표시를 클릭할 경우 삭제 되게 하였습니다.
- 게시물에서 다른 사람의 책장을 볼경우 수정이 필요할거 같습니다.

[Feat]: 나의 책장 기능 구현

---

BookBridge/BookBridge/Utility/Manager/UserManager.swift
BookBridge/BookBridge/ViewModel/HomeViewModel.swift
BookBridge/BookBridge/ViewModel/Post/PostViewModel.swift
BookBridge/BookBridge/ViewModel/PostingViewModel.swift
BookBridge/BookBridge/Views/HomeTap/HomeListItemView.swift
BookBridge/BookBridge/Views/HomeTap/HomeTapView.swift
BookBridge/BookBridge/Views/HomeTap/HomeView.swift
BookBridge/BookBridge/Views/Post/PostView.swift

- 제목 : Feat(100): 홈 로그인 아이디 연동
어떤 변경 사항이 있나요?
- 로그인 시 로그인, 비로그인 체크 및 로그인 아이디 연동
<br/>
- [PJ3T6_BookBridge #100 ](https://github.com/APP-iOS3rd/PJ3T6_BookBridge/issues/100)
<br/>

Feat(100): 홈 로그인 아이디 연동

---

BookBridge/BookBridge.xcodeproj/project.pbxproj
BookBridge/BookBridge/Model/Report.swift
BookBridge/BookBridge/ViewModel/Report/ReportViewModel.swift
BookBridge/BookBridge/Views/Report/ReportDetailView.swift
BookBridge/BookBridge/Views/Report/ReportView.swift

어떤 변경 사항이 있나요?
1. 신고하기 View 추가
2. 신고하기 상세 View, 알림창 추가
3. Cell클릭시 Contents내용 다음 화면 Title 적용
4. 알림창 확인시 신고하기 전 화면 (게시글 or 채팅) 돌아가기 => 임시로 HomeView
5. 신고하기 Model설정
6. 파이어베이스 연동
7. UserManger를 ID활용하여 저장시 UserID 저장
8. 비동기 처리 FireStore저장
<br/>
<br/>
- ex) [PJ3T6_BookBridge #81]
<br/>

Feat : 신고하기 VIew 및 기능 개발

---

BookBridge/BookBridge.xcodeproj/project.pbxproj
BookBridge/BookBridge/Views/Report/ReportCellView.swift

어떤 변경 사항이 있나요?
누락된 ReportCellView 추가
<br/>
<br/>

[Fix] : 누락된 ReportCellView 추가

---

BookBridge/BookBridge.xcodeproj/project.pbxproj
BookBridge/BookBridge/Model/NoticeBoardModel.swift
BookBridge/BookBridge/Utility/Manager/Firestore/FirestoreManager.swift
BookBridge/BookBridge/Utility/Manager/UserManager.swift
BookBridge/BookBridge/ViewModel/HomeViewModel.swift
BookBridge/BookBridge/ViewModel/PostingViewModel.swift
BookBridge/BookBridge/Views/Posting/ChangePostingView.swift
BookBridge/BookBridge/Views/Posting/FindPostingView.swift

어떤 변경 사항이 있나요?
- 게시글 posting 시에 geohash 추가 저장 기능 구현
<br/>
- [PJ3T6_BookBridge #107 ](https://github.com/APP-iOS3rd/PJ3T6_BookBridge/issues/107)
<br/>

feat(107): geohash 저장 기능 구현

---

BookBridge/BookBridge.xcodeproj/project.pbxproj
BookBridge/BookBridge/BookBridgeApp.swift
BookBridge/BookBridge/ViewModel/LocationViewModel.swift

어떤 변경 사항이 있나요?
현재위치 권한설정 로직 변경하여 오류를 해결하였습니다.
<br/>
- ex) [PJ3T6_BookBridge #111]
<br/>

Fix(111): 현재위치 권한 설정 오류 수정

---

BookBridge/BookBridge.xcodeproj/project.pbxproj
BookBridge/BookBridge/BookBridgeApp.swift
BookBridge/BookBridge/Model/Enum/PathType.swift
BookBridge/BookBridge/TabBarView.swift
BookBridge/BookBridge/Utility/Manager/UserManager.swift
BookBridge/BookBridge/Views/BookShelf/AddBookBtnView.swift
BookBridge/BookBridge/Views/BookShelf/BookDetailView.swift
BookBridge/BookBridge/Views/BookShelf/BookShelfView.swift
BookBridge/BookBridge/Views/BookShelf/WishBookAddBtnView.swift
BookBridge/BookBridge/Views/HomeTap/HomeView.swift
BookBridge/BookBridge/Views/Login/IdLogin/IdLoginView.swift
BookBridge/BookBridge/Views/Login/KaKaoLogin/KakaoLoginView.swift
BookBridge/BookBridge/Views/Login/LoginView.swift
BookBridge/BookBridge/Views/Post/PostView.swift

어떤 변경 사항이 있나요?
- tabbarView에서 부터 화면이 시작하게 되었으며 LoginView를 Sheet로 설정하였습니다
- 로그인이 되어있지 않을경우 Alert을 띄워 로그인을 할지 물어보며 로그인을 한다면 LoginView가 나타나게 됩니다.
- 책장을 사용할때 tapInfo를 추가하여 희망도서에서 추가했는지 보유도서에서 추가했는지 알수있게 하였습니다
- 희망도서추가를 눌렀을때 화면이 제대로 나오지 않는 오류를 발견해 수정하였습니다.
<br/>

[Feat]: NavigationStack 변경

---

BookBridge/BookBridge.xcodeproj/project.pbxproj
BookBridge/BookBridge/BookBridgeApp.swift
BookBridge/BookBridge/Utility/Manager/Firestore/FirestoreSignUpManager.swift
BookBridge/BookBridge/Utility/Manager/GeohashManager.swift
BookBridge/BookBridge/Utility/Manager/UserManager.swift
BookBridge/BookBridge/ViewModel/HomeViewModel.swift
BookBridge/BookBridge/Views/HomeTap/HomeTapView.swift

- 제목 : Feat(issue 번호): 기능명
ex) feat(17): pull request template 작성
(확인 후 지워주세요)
어떤 변경 사항이 있나요?
게시물의 좌표와 geohash를 이용하여 현재 사용자로부터 정해진 거리의 게시물들을 불러오는 기능을 구현하였습니다.
<br/>
비로그인시 사용자 현재 위치를 기반으로 1km내에 위치한 게시물들을 불러옵니다.
<br/>
- ex) [PJ3T6_BookBridge #107]
<br/>

Feat(107): geohash 적용 게시물 불러오기 기능 (바꿔요) 

---

BookBridge/BookBridge.xcodeproj/project.pbxproj
BookBridge/BookBridge/Utility/Manager/Firestore/FirestoreManager.swift
BookBridge/BookBridge/Utility/Manager/Firestore/FirestoreSignUpManager.swift
BookBridge/BookBridge/Utility/Manager/UserManager.swift
BookBridge/BookBridge/ViewModel/Login/GoogleAuthViewModel.swift
BookBridge/BookBridge/ViewModel/PostingViewModel.swift

어떤 변경 사항이 있나요?
- FirestoreManager UserModel fetch 기능 구현
- 로그인시 UserModel fetch 적용
- 구글 회원가입시 후 바로 로그인 적용
<br/>
<br/>
로그인에 성공하면 UserModel을 생성합니다.
- ex) [PJ3T6_BookBridge #120]
<br/>

Feat(120): 로그인시 UserManager에 UserModel fetch

---

BookBridge/BookBridge.xcodeproj/project.pbxproj
BookBridge/BookBridge/BookBridgeApp.swift
BookBridge/BookBridge/Model/Chat/ChatPartnerModel.swift
BookBridge/BookBridge/ViewModel/Chat/ChatMessageViewModel.swift
BookBridge/BookBridge/ViewModel/Chat/ChatRoomListViewModel.swift
BookBridge/BookBridge/Views/Chat/ChatBottomBarView.swift
BookBridge/BookBridge/Views/Chat/ChatMessageView.swift
BookBridge/BookBridge/Views/Chat/ChatRoomListView.swift
BookBridge/BookBridge/Views/Chat/CustomNavBarView.swift
BookBridge/BookBridge/Views/Chat/MessageItemView.swift
BookBridge/BookBridge/Views/Chat/MessageListView.swift
BookBridge/BookBridge/Views/Chat/RoomListView.swift
BookBridge/BookBridge/Views/Chat/SearchChatListView.swift
BookBridge/BookBridge/Views/Chat/noticeBoardChatView.swift

[Refactor] Chat logic

---

BookBridge/BookBridge/ViewModel/Chat/ChatMessageViewModel.swift
BookBridge/BookBridge/Views/Chat/ChatBottomBarView.swift
BookBridge/BookBridge/Views/Chat/MessageItemView.swift
BookBridge/BookBridge/Views/Chat/MessageListView.swift
BookBridge/BookBridge/Views/Chat/NoticeBoardChatView.swift

[Feat] 채팅 로직

---

BookBridge/BookBridge/Views/Post/PostView.swift

- postModifyView 를 merge 하면서 생긴 에러 수정
<br/>

[Fix] merge 에러 수정

---

BookBridge/BookBridge.xcodeproj/project.pbxproj
BookBridge/BookBridge.xcworkspace/xcshareddata/swiftpm/Package.resolved
BookBridge/BookBridge/Model/NoticeBoardModel.swift
BookBridge/BookBridge/Model/UserModel.swift
BookBridge/BookBridge/Utility/Manager/Firestore/FirestoreSignUpManager.swift
BookBridge/BookBridge/ViewModel/PostingViewModel.swift
BookBridge/BookBridge/Views/Post/PostView.swift

어떤 변경 사항이 있나요?
- UserModel 요소 추가
- NoticeBoard 요소 추가
- 게시물 생성시 좌표 현재 동네 좌표로 수정
<br/>

[Refactor]: 게시물 좌표 수정

---

BookBridge/BookBridge/Views/Post/PostView.swift

- 게시글에서 채팅 네비게이션 기능 추가
<br/>
- [[PJ3T6_BookBridge #142 ](https://github.com/APP-iOS3rd/PJ3T6_BookBridge/issues/142)
<br/>

Feat(142): 게시글 채팅 네비게이션

---

BookBridge/BookBridge.xcodeproj/project.pbxproj
BookBridge/BookBridge/SelectPostingView.swift
BookBridge/BookBridge/TabBarView.swift
BookBridge/BookBridge/Views/Chat/ChatBottomBarView.swift
BookBridge/BookBridge/Views/Chat/ChatMessageView.swift
BookBridge/BookBridge/Views/Chat/ChatRoomListView.swift
BookBridge/BookBridge/Views/Chat/MessageItemView.swift
BookBridge/BookBridge/Views/Chat/NoticeBoardChatView.swift
BookBridge/BookBridge/Views/Chat/RoomListView.swift
BookBridge/BookBridge/Views/HomeTap/HomeTapView.swift
BookBridge/BookBridge/Views/HomeTap/HomeView.swift
BookBridge/BookBridge/Views/Post/PostView.swift
BookBridge/BookBridge/Views/Posting/ChangePostingView.swift
BookBridge/BookBridge/Views/Posting/FindPostingView.swift
BookBridge/BookBridge/Views/Report/ReportDetailView.swift

[Feat] 탭바 커스텀
어떤 변경 사항이 있나요?
- 플러스 버튼 눌렀을 때 나오는 창 변경
- 플러스 버튼 화면 이동 시에 숨김 및 보이기
<br/>
<br/>

[Feat] 탭바 커스텀

---

BookBridge/BookBridge.xcodeproj/project.pbxproj
BookBridge/BookBridge/Utility/Manager/Firestore/FirestoreManager.swift
BookBridge/BookBridgeTests/FirestoreManager_Tests.swift

어떤 변경 사항이 있나요?
- firestore에서 hopeBook fetch 기능 구현
<br/>

Feat: hopeBook fetch 기능 구현

---

BookBridge/BookBridge.xcodeproj/project.pbxproj
BookBridge/BookBridge/TabBarView.swift
BookBridge/BookBridge/ViewModel/Chat/ChatMessageViewModel.swift
BookBridge/BookBridge/ViewModel/Chat/ChatRoomListViewModel.swift
BookBridge/BookBridge/Views/Chat/ChatBottomBarView.swift
BookBridge/BookBridge/Views/Chat/ChatMessageView.swift

어떤 변경 사항이 있나요?
- 기능에서 어떤 부분이 구현되었는지 설명해주세요
<br/>
<br/>
- ex) [PJ3T6_BookBridge #146 ]
<br/>

Feat : FCM을 활용한 채팅 push알람 재요청 드려요

---

BookBridge/BookBridge.xcodeproj/project.pbxproj
BookBridge/BookBridge/Views/BookShelf/BookShelfView.swift
BookBridge/BookBridge/Views/Post/PostView.swift

어떤 변경 사항이 있나요?
- 게시물에서 책장 넘어가는 Navigationtitle 부분 수정하였습니다.
<br/>

[Refactor]: 게시물에서 책장 넘어갈때 NavigationTitle 수정

---

BookBridge/BookBridge/ViewModel/Post/PostModifyViewModel.swift
BookBridge/BookBridge/ViewModel/PostingViewModel.swift
BookBridge/BookBridge/Views/Post/ChangePostingModifyView.swift
BookBridge/BookBridge/Views/Post/ExChangeHopeModifyView.swift
BookBridge/BookBridge/Views/Post/FindPostingModifyView.swift
BookBridge/BookBridge/Views/Post/PostView.swift
BookBridge/BookBridge/Views/Posting/ChangePostingView.swift
BookBridge/BookBridge/Views/Posting/ExchangeHopeExplainView.swift
BookBridge/BookBridge/Views/Posting/ExchangeHopeView.swift
BookBridge/BookBridge/Views/Posting/FindPostingView.swift

- 네비게이션 뷰 추가
- posting 할때 isbn 없을때 튕기는 오류 수정
- 수정하기 희망도서 설정 기능 구현
- 맵뷰, 포스팅뷰 툴바 dismiss 버튼 디자인 수정
<br/>
<br/>
- [PJ3T6_BookBridge #131](https://github.com/APP-iOS3rd/PJ3T6_BookBridge/issues/131)
<br/>

Feat(131) 수정하기

---

BookBridge/BookBridge.xcodeproj/project.pbxproj
BookBridge/BookBridge/BookBridgeApp.swift
BookBridge/BookBridge/Model/UserModel.swift
BookBridge/BookBridge/TabBarView.swift
BookBridge/BookBridge/Utility/Manager/Firestore/FirestoreManager.swift
BookBridge/BookBridge/Utility/Manager/Firestore/FirestoreSignUpManager.swift
BookBridge/BookBridge/ViewModel/HomeViewModel.swift
BookBridge/BookBridge/ViewModel/MyProfileViewModel.swift
BookBridge/BookBridge/ViewModel/ReviewScoreViewModel.swift
BookBridge/BookBridge/Views/HomeTap/HomeTapView.swift
BookBridge/BookBridge/Views/MyPage/AccountManagementView.swift
BookBridge/BookBridge/Views/MyPage/MyProfileNicknameView.swift
BookBridge/BookBridge/Views/MyPage/MyProfilePasswordView.swift
BookBridge/BookBridge/Views/MyPage/MyProfileToolbarItemView.swift
BookBridge/BookBridge/Views/MyPage/MyProfileView.swift
BookBridge/BookBridge/Views/MyPage/ReviewScoreView.swift

어떤 변경 사항이 있나요?
- 오타 수정
- 매너점수 로직 수정
- 프로필 부분 UI 수정
- 프로필 부분 비밀번호 수정 추가
<br/>
<br/>

[Refactor] 여러가지 로직 및 비밀번호 수정 추가

---

BookBridge/BookBridge/TabBarView.swift
BookBridge/BookBridge/Utility/Manager/Firestore/FirestoreManager.swift
BookBridge/BookBridge/Utility/Manager/Login/NaverAuthManager.swift
BookBridge/BookBridge/Utility/Manager/UserManager.swift
BookBridge/BookBridge/ViewModel/HomeViewModel.swift
BookBridge/BookBridge/ViewModel/Login/KakaoLoginViewModel.swift
BookBridge/BookBridge/Views/BookShelf/BookView.swift
BookBridge/BookBridge/Views/HomeTap/HomeRecentSearchView.swift
BookBridge/BookBridge/Views/HomeTap/HomeTapView.swift
BookBridge/BookBridge/Views/Login/AppleLogin/AppleLoginView.swift
BookBridge/BookBridge/Views/MyPage/SettingView.swift
BookBridge/BookBridge/Views/Post/PostMenuBtnsView.swift

어떤 변경 사항이 있나요?
- 비로그인시 최근 검색 기록 오류 해결하였습니다.
- 로그인 alert 대신 loginview가 sheet로 나오게 변경하였습니다.
- 게시물 삭제시 alert창 띄우게 하였습니다.
- 책장 이미지를 kingfisher와 연동하게 아였습니다.
- 회원탈퇴시 카카오,네이버 토큰을 삭제하게 하였습니다.
- 최근검색 TextField를 scroll에서 제거 하였습니다.
- 애플로그인 화면에서 조건문을 제거 하였습니다.

Search post

---

BookBridge/BookBridge.xcodeproj/project.pbxproj
BookBridge/BookBridge/BookBridgeApp.swift
BookBridge/BookBridge/Views/HomeTap/HomeListItemView.swift
BookBridge/BookBridge/Views/LaunchScreen/LaunchScreenView.swift
BookBridge/BookBridge/Views/Post/FindPostingModifyView.swift

어떤 변경 사항이 있나요?
-  launchScreen 추가, 게시글 수정 오류 수정
<br/>
-  [PJ3T6_BookBridge #131 ](https://github.com/APP-iOS3rd/PJ3T6_BookBridge/issues/131)
<br/>

Feat(131): LaunchScreen, 수정하기

---

BookBridge/BookBridge/Utility/Manager/ConvertManager.swift
BookBridge/BookBridge/ViewModel/PostingViewModel.swift
BookBridge/BookBridge/Views/HomeTap/HomeListItemView.swift
BookBridge/BookBridge/Views/Post/PostChangeLocationView.swift
BookBridge/BookBridge/Views/Post/PostUserInfoView.swift
BookBridge/BookBridge/Views/Post/PostView.swift
BookBridge/BookBridge/Views/Posting/ChangePostingView.swift

어떤 변경 사항이 있나요?
- 교환장소 선택시 게시물 위치 교환장소로 변경
- 교환장소 상세주소 추가
- 구해요 게시물 실시간 업로드
<br/>

Refactor: 교환장소 기반 게시물 위치 변경

---

BookBridge/BookBridge.xcodeproj/project.pbxproj
BookBridge/BookBridge/TabBarView.swift
BookBridge/BookBridge/ViewModel/Post/PostModifyViewModel.swift
BookBridge/BookBridge/ViewModel/Post/PostViewModel.swift
BookBridge/BookBridge/Views/BookShelf/BookDetailView.swift
BookBridge/BookBridge/Views/BookShelf/BookShelfView.swift
BookBridge/BookBridge/Views/BookShelf/BookView.swift
BookBridge/BookBridge/Views/HomeTap/HomeListItemView.swift
BookBridge/BookBridge/Views/HomeTap/HomeTapView.swift
BookBridge/BookBridge/Views/Login/Find/ID/FindIdView.swift
BookBridge/BookBridge/Views/Login/IdLogin/IdLoginView.swift
BookBridge/BookBridge/Views/Post/BookShelfHeaderView.swift
BookBridge/BookBridge/Views/Post/ChangePostingModifyView.swift
BookBridge/BookBridge/Views/Post/FindPostingModifyView.swift
BookBridge/BookBridge/Views/Post/PostHopeBookListView.swift
BookBridge/BookBridge/Views/Post/PostUserBookshelf.swift
BookBridge/BookBridge/Views/Post/PostView.swift
BookBridge/BookBridge/Views/SearchBook/SearchBooksView.swift

어떤 변경 사항이 있나요?
- 바꿔요 게시물의 게시물 내용을 보여지게하였습니다
- 게시물 삭제부분에 문제가 있어 수정하였습니다.
- 게시물 수정시 뒤로가기 버튼을 X에서 < 로 수정하였습니다.
- 구해요 게시물에서 게시물 희망도서View를 추가하였습니다.
- 교환희망장소가 너무 길 경우 동만 보이게 변경하였습니다.
- 더보기에서 책장 부분을 들어가서 탭할경우 + 버튼이 생성되는 기능을 수정하였습니다.
<br/>

희망도서 목록 추가

---

BookBridge/BookBridge/Views/MyPage/SettingView.swift
BookBridge/BookBridge/Views/Post/PostView.swift

어떤 변경 사항이 있나요?
- 바꿔요 게시물에서는 희망도서 목록이 안보이게 처리하였습니다.
- 로그아웃시 dismiss 기능을 추가하였습니다.
<br/>

[Fix]: 바꿔요 게시물에서는 희망도서 목록 안보이게 처리

---

BookBridge/BookBridge/ViewModel/Chat/ChatMessageViewModel.swift
BookBridge/BookBridge/ViewModel/Post/PostViewModel.swift
BookBridge/BookBridge/Views/Chat/ChatMessageView.swift
BookBridge/BookBridge/Views/Chat/NoticeBoardChatView.swift

어떤 변경 사항이 있나요?
- 기능에서 어떤 부분이 구현되었는지 설명해주세요
<br/>
<br/>

[Feat] 채팅방 나가기, 게시물 삭제할 때 처리

---

BookBridge/BookBridge/TabBarView.swift
BookBridge/BookBridge/Views/HomeTap/HomeListItemView.swift
BookBridge/BookBridge/Views/HomeTap/HomeTapView.swift

어떤 변경 사항이 있나요?
- 게시물 사이에 Divider를 추가했습니다
<br/>

[Refactor]: List사이에 Divider 추가

---

BookBridge/BookBridge/ViewModel/Post/PostViewModel.swift
BookBridge/BookBridge/Views/BookShelf/BookShelfView.swift
BookBridge/BookBridge/Views/Post/PostMenuBtnsView.swift

어떤 변경 사항이 있나요?
- 게시물 삭제 로직 변경
- alert 내용 및 오류 수정
<br/>
<br/>

[Refactor] alert 수정 및 삭제 로직 코드 변경

---

BookBridge/BookBridge/Views/HomeTap/HomeTapView.swift
BookBridge/BookBridge/Views/Login/Find/ID/FindIdView.swift
BookBridge/BookBridge/Views/Login/Find/Password/FindPasswordView.swift
BookBridge/BookBridge/Views/Login/IdLogin/IdLoginView.swift

어떤 변경 사항이 있나요?
- 홈탭뷰 색상을 변경하였습니다
- 스크롤뷰를 아래로 내리면 새로고침하게 되었습니다.
- 로그인뷰에서 사진이 짤리는 문제를 해결하였습니다.

[Refactor]: HomeTapView,LoginView 리팩토링

---

BookBridge/BookBridge/Views/MyPage/NoticeBoardItemView.swift
BookBridge/BookBridge/Views/MyPage/NoticeBoardTapView.swift

어떤 변경 사항이 있나요?
- 내 게시물에서 보이는 동과 시간을 수정하였습니다.
<br/>

[Refactor]: 내 게시물 동, 시간 수정

---

BookBridge/BookBridge.xcodeproj/project.pbxproj
BookBridge/BookBridge/Utility/Extension/UIColorExtension.swift
BookBridge/BookBridge/Utility/Manager/ConvertManager.swift
BookBridge/BookBridge/ViewModel/Map/LocationViewModel.swift
BookBridge/BookBridge/ViewModel/Map/UserLocationViewModel.swift
BookBridge/BookBridge/Views/TownSetting/TownSettingSlideView.swift

어떤 변경 사항이 있나요?
- 동네설정 마커 사라지는 현상 수정
- 동네설정 overlay에서 marker로 변경
- 범위를 표시하는 원형 색상 변경
<br/>
<br/>
기기에서 실행한 화면입니다.
<br/>
[PJ3T6_BookBridge #212 ]
<br/>

fix(212): 동네설정 실기기 마커안뜨는 현상 해결

---

BookBridge/BookBridge/ViewModel/Login/IdLoginViewModel.swift
BookBridge/BookBridge/ViewModel/Login/SignUpViewModel.swift
BookBridge/BookBridge/Views/Login/EmailSignUp/EmailCertiView.swift
BookBridge/BookBridge/Views/Login/IdLogin/IdLoginView.swift

어떤 변경 사항이 있나요?
- 로그인시 로그인버튼에 로딩 표시 추가
- 인증 번호 3분으로 수정
- 비밀번호 찾기시 아이디와 이메일이 동시에 입력되게 되어 있어 수정하였습니다.
<br/>

[Refactor]: 로그인 부분 리팩토링

---

BookBridge/BookBridge.xcodeproj/project.pbxproj
BookBridge/BookBridge/Utility/Manager/LocationManager.swift
BookBridge/BookBridge/ViewModel/Map/LocationViewModel.swift
BookBridge/BookBridge/ViewModel/Map/UserLocationViewModel.swift
BookBridge/BookBridge/Views/Alert/LocationPermitView.swift
BookBridge/BookBridge/Views/TownSetting/TownSettingView.swift

어떤 변경 사항이 있나요?
- 위치권한을 허용안됨으로 선택시 기본 위치 서울시청으로 변경
- 위치권환 변경 안내 캡션 추가
<br/>
<br/>
[PJ3T6_BookBridge #212]
<br/>

Refactor(212): 위치권환 허용안됨 로직 변경

---

BookBridge/BookBridge/Info.plist
BookBridge/BookBridge/ViewModel/Chat/ChatMessageViewModel.swift
BookBridge/BookBridge/ViewModel/MyPage/SettingViewModel.swift
BookBridge/BookBridge/Views/MyPage/AlarmSettingView.swift

어떤 변경 사항이 있나요?
* push알림 클라우드 원격서버 IP변경
* 채팅알람을 제외한 나머지 알람설정 제거
* 채팅 알림 토글 클릭시 FireStore 유저 정보 갱신
* 채팅 알림 화면 띄울때 FireStore 유저 정보에 채팅 알림을 불러오기 추가
<br/>
<br/>
[PJ3T6_BookBridge #218]
<br/>

[Fix] 채팅 Push알림 수정건

---

BookBridge/BookBridge/Utility/Manager/Firestore/FirestoreSignUpManager.swift
BookBridge/BookBridge/Utility/Manager/Login/NaverAuthManager.swift
BookBridge/BookBridge/ViewModel/Login/ChangePasswordVM.swift
BookBridge/BookBridge/ViewModel/Login/IdLoginViewModel.swift
BookBridge/BookBridge/ViewModel/Login/KakaoLoginViewModel.swift
BookBridge/BookBridge/ViewModel/Login/SignUpViewModel.swift
BookBridge/BookBridge/Views/Login/Find/Password/FindPasswordView.swift
BookBridge/BookBridge/Views/Login/IdLogin/IdLoginView.swift
BookBridge/BookBridge/Views/Login/KaKaoLogin/KakaoLoginView.swift

어떤 변경 사항이 있나요?
- 로그인이 실패할 경우 alert창을 생성하였습니다.
- 카카오로그인시 해당 이메일이 있을경우 로그인은 실패하고 alert창을 생성합니다.
<br/>

[Feat]: 로그인 실패시 Alert 생성 && 카카오 로그인시 이메일 중복일 경우 Alert생성

---

BookBridge/BookBridge/Utility/Manager/Login/NaverAuthManager.swift
BookBridge/BookBridge/Views/Login/NaverLogin/NaverLoginView.swift

어떤 변경 사항이 있나요?
- 네이버 로그인시 이미 가입된 이메일이 있을경우 Alert이 생성됩니다.
<br/>

[Feat]: 네이버 로그인시 이메일 중복일 경우 Alert 생성

---

BookBridge/BookBridge/Views/Chat/ChatRoomListView.swift

어떤 변경 사항이 있나요?
- 로그아웃시 채팅방이 없다 화면이 나오게 변경
<br/>

[Fix]: 로그아웃시 채팅화면 변경

---

BookBridge/BookBridge.xcodeproj/project.pbxproj
BookBridge/BookBridge/Views/Alert/ToastMessageView.swift
BookBridge/BookBridge/Views/Post/PostChangeLocationView.swift

- 제목 : Feat(issue 번호): 기능명
ex) feat(17): pull request template 작성
(확인 후 지워주세요)
어떤 변경 사항이 있나요?
- 주소 복사 기능 추가
<br/>
<br/>
-  [PJ3T6_BookBridge #224](https://github.com/APP-iOS3rd/PJ3T6_BookBridge/issues/224)
<br/>

 Feat(224): 주소 복사 기능 추가

---

BookBridge/BookBridge.xcodeproj/project.pbxproj
BookBridge/BookBridge/Model/BookModel.swift
BookBridge/BookBridge/Model/Chat/ChatPartnerModel.swift
BookBridge/BookBridge/Model/Enum/Location.swift
BookBridge/BookBridge/Model/Enum/TabPathType.swift
BookBridge/BookBridge/Model/NoticeBoardModel.swift
BookBridge/BookBridge/Model/UserModel.swift
BookBridge/BookBridge/TabBarView.swift
BookBridge/BookBridge/ViewModel/Chat/ChatRoomListViewModel.swift
BookBridge/BookBridge/ViewModel/MyPageViewModel.swift
BookBridge/BookBridge/ViewModel/NoticeBoardViewModel.swift
BookBridge/BookBridge/ViewModel/TabPathViewModel.swift
BookBridge/BookBridge/Views/Chat/ChatMessageView.swift
BookBridge/BookBridge/Views/Chat/MessageItemView.swift
BookBridge/BookBridge/Views/Chat/MessageListView.swift
BookBridge/BookBridge/Views/Chat/NoticeBoardChatView.swift
BookBridge/BookBridge/Views/Chat/RoomListView.swift
BookBridge/BookBridge/Views/HomeTap/HomeTapView.swift
BookBridge/BookBridge/Views/HomeTap/HomeView.swift
BookBridge/BookBridge/Views/MyPage/AccountManagementView.swift
BookBridge/BookBridge/Views/MyPage/MyPageView.swift
BookBridge/BookBridge/Views/MyPage/MyPostView.swift
BookBridge/BookBridge/Views/MyPage/NoticeBoardTapView.swift
BookBridge/BookBridge/Views/MyPage/NoticeBoardView.swift
BookBridge/BookBridge/Views/Post/ExChangeHopeModifyView.swift
BookBridge/BookBridge/Views/Post/PostUserInfoView.swift
BookBridge/BookBridge/Views/Post/PostView.swift

어떤 변경 사항이 있나요?
- tabbar에서 NavigationStack을 시작해서 MyPageView,PostView,ChatMessageView,ChatRoomListView를 연결했습니다
- 홈화면을 누르면 모든 stack이 삭제되고 홈화면으로 돌아가게 하였습니다.
<br/>

NavigationStack으로 변경

---

BookBridge/BookBridge/Views/Chat/ChatRoomListView.swift
BookBridge/BookBridge/Views/Chat/MessageItemView.swift
BookBridge/BookBridge/Views/HomeTap/HomeListItemView.swift
BookBridge/BookBridge/Views/HomeTap/HomeView.swift
BookBridge/BookBridge/Views/MyPage/MyPageView.swift
BookBridge/BookBridge/Views/MyPage/NoticeBoardTapView.swift
BookBridge/BookBridge/Views/MyPage/NoticeBoardView.swift
BookBridge/BookBridge/Views/Post/PostUserInfoView.swift
BookBridge/BookBridge/Views/Post/PostView.swift

어떤 변경 사항이 있나요?
- conflict에서 정리되지 않았던 코드들을 수정하였습니다.

Conflict에서 생긴 오류 수정

---

BookBridge/BookBridge.xcodeproj/project.pbxproj
BookBridge/BookBridge/Info.plist

어떤 변경 사항이 있나요?
- 앱 시작시 런치스크린 추가
<br/>

[Feat] launch Screen 추가

---

BookBridge/BookBridge/Model/NoticeBoardModel.swift
BookBridge/BookBridge/Utility/Manager/GeohashManager.swift
BookBridge/BookBridge/ViewModel/PostingViewModel.swift
BookBridge/BookBridge/Views/Login/Find/ID/FindIdView.swift
BookBridge/BookBridge/Views/Post/PostView.swift

어떤 변경 사항이 있나요?
- 교환희망장소 선택안할시 게시물에서 교환희망장소 비활성화
<br/>

[Refactor] 교환희망장소 비활성화

---

BookBridge/BookBridge.xcodeproj/project.pbxproj
BookBridge/BookBridge/TabBarView.swift
BookBridge/BookBridge/Views/MyPage/PrivacypolicyView.swift
BookBridge/BookBridge/Views/MyPage/PrivacypolicyWebView.swift
BookBridge/BookBridge/Views/MyPage/SettingView.swift
BookBridge/BookBridge/Views/Posting/ExchangeHopeView.swift

어떤 변경 사항이 있나요?
- WebKit을 이용하여 notion페이지를 연결하였습니다.
- 아이폰 11,12에서 상단View 오류를 해결하였습니다.
<br/>

[Feat]: 개인정보처리방침View 생성

---

BookBridge/BookBridge/ViewModel/NotificationViewModel.swift

어떤 변경 사항이 있나요?
- firestore의 User를 탐색해서 바로바로 상대방 유저의 이미지를 로드하게 변경하였습니다.

[Feat]: 실시간 유저 이미지 불러오는 기능 추가

---

BookBridge/BookBridge/ViewModel/NotificationViewModel.swift
BookBridge/BookBridge/Views/HomeTap/NotificationView.swift
BookBridge/BookBridge/Views/Review/ExchangeReview.swift

어떤 변경 사항이 있나요?
-  알림 삭제 로직 추가 및 전송 로직 수정

[Feat] 알림 삭제 로직 추가 및 전송 로직 수정

---

BookBridge/BookBridge/Views/Posting/CameraModalView.swift

어떤 변경 사항이 있나요?
- 바꿔요 게시물 생성 사진, 동영상 아이콘 채팅방이랑 통일하기
<br/>

[Fix]: 사진, 카메라 색상 변경

---

BookBridge/BookBridge/ViewModel/NotificationViewModel.swift

어떤 변경 사항이 있나요?
- 함수 중복 실행 삭제
<br/>

[Fix] 함수 중복 실행 삭제

---

BookBridge/BookBridge/TabBarView.swift
BookBridge/BookBridge/ViewModel/Chat/ChatMessageViewModel.swift

어떤 변경 사항이 있나요?
- 기능에서 어떤 부분이 구현되었는지 설명해주세요
<br/>
<br/>

[Refactor] 칭호 및 내 게시물 상태 수정

---

BookBridge/BookBridge.xcodeproj/project.pbxproj
BookBridge/BookBridge/BookBridgeApp.swift
BookBridge/BookBridge/Views/Login/EmailSignUp/AgreeView.swift
BookBridge/BookBridge/Views/Login/EmailSignUp/EmailCertiView.swift
BookBridge/BookBridge/Views/Login/EmailSignUp/EmailSignUpView.swift
BookBridge/BookBridge/Views/Login/EmailSignUp/SignUpInputBoxView.swift

어떤 변경 사항이 있나요?
- 회원가입전 최소연령 확인 및 약과 동의사항을 만들었습니다
- 둘다 체크를 한뒤 계속하기를 눌러야 이메일이 보내지며 계속하기를 누르지 않고 그냥 sheet는 내리면 다시 올라오게 됩니다
- 14세 미만으로 계속하기 버튼을 누를경우 sheet가 닫히면서 회원가입 페이지도 나가게 했습니다.
<br/>

개인 정보 처리 확인VIew

---

BookBridge/BookBridge.xcodeproj/project.pbxproj
BookBridge/BookBridge/Views/MyPage/AccountManagementView.swift
BookBridge/BookBridge/Views/MyPage/AlarmSettingView.swift
BookBridge/BookBridge/Views/MyPage/BlockUserManagementView.swift
BookBridge/BookBridge/Views/MyPage/MyPageView.swift
BookBridge/BookBridge/Views/MyPage/MyPostView.swift
BookBridge/BookBridge/Views/MyPage/SettingView.swift
BookBridge/BookBridge/Views/MyPage/StyleListView.swift
BookBridge/BookBridge/Views/MyPage/TermsAndConditionsView.swift

- 제목 : [Refactor] 마이페이지 메뉴리스트 선 Divider로 변경
어떤 변경 사항이 있나요?
- 마이페이지 리스트 굵게 나오던 선 변경
<br/>
<br/>
- ex) [PJ3T6_BookBridge #84]
<br/>

[Refactor] 마이페이지 메뉴리스트 선 Divider로 변경

---

BookBridge/BookBridge.xcodeproj/project.pbxproj
BookBridge/BookBridge/Info.plist
BookBridge/BookBridge/Views/TownSetting/TownSettingView.swift

- 제목 : [Fix] 동네설정 디바이스별 비율 오류 수정
어떤 변경 사항이 있나요?
- 동네설정 디바이스별 비율 맞게 조정
- 카메라 한글화
<br/>
<br/>
- ex) [PJ3T6_BookBridge #84]
<br/>

[Fix] 동네설정 디바이스별 비율 오류 수정

---

BookBridge/BookBridge/ViewModel/Map/UserLocationViewModel.swift

어떤 변경 사항이 있나요?
- 동네설정 지도 확대 비활성
<br/>

fix: 동네설정 지도 확대 비활성

---

BookBridge/BookBridge/Model/UserModel.swift
BookBridge/BookBridge/ViewModel/HomeViewModel.swift
BookBridge/BookBridge/ViewModel/Post/PostViewModel.swift
BookBridge/BookBridge/Views/HomeTap/HomeTapView.swift
BookBridge/BookBridge/Views/HomeTap/HomeView.swift
BookBridge/BookBridge/Views/Post/PostMenuBtnsView.swift

- 제목 : [Feat] 유저 차단 및 게시글 숨김 기능
- 
어떤 변경 사항이 있나요?
- 유저 차단 및 게시글 숨김 기능

[Feat] 유저 차단 및 게시글 숨김 기능

---

BookBridge/BookBridge/Views/HomeTap/HomeView.swift

[Fix] 로그아웃시 차단목록 fetch 로 인한 버그 해결
어떤 변경 사항이 있나요?
- 로그아웃시 차단목록 fetch 로 인한 버그 해결
<br/>

[Fix] 로그아웃시 차단목록 fetch 로 인한 버그 해결

---

BookBridge/BookBridge/Model/NotificationModel.swift
BookBridge/BookBridge/ViewModel/NotificationViewModel.swift
BookBridge/BookBridge/Views/HomeTap/HomeView.swift
BookBridge/BookBridge/Views/HomeTap/NotificationView.swift
BookBridge/BookBridge/Views/Review/ExchangeReview.swift

어떤 변경 사항이 있나요?
- 한번 알람버튼 클릭시 뱃지 비활성
- 상대방 평과 확인 및 확인 메세지 발송
- 상대방 평과 확인시 평가기능 비활성
<br/>
<br/>

Refactor: 알람기능 실시간 반영 기능

---

BookBridge/BookBridge/ViewModel/NotificationViewModel.swift
BookBridge/BookBridge/ViewModel/PostingViewModel.swift
BookBridge/BookBridge/Views/Chat/ChatBottomBarView.swift
BookBridge/BookBridge/Views/Chat/NoticeBoardChatView.swift
BookBridge/BookBridge/Views/HomeTap/NotificationView.swift
BookBridge/BookBridge/Views/Login/IdLogin/IdLoginView.swift
BookBridge/BookBridge/Views/Post/PostMenuBtnsView.swift
BookBridge/BookBridge/Views/Posting/ChangePostingView.swift
BookBridge/BookBridge/Views/Posting/FindPostingView.swift
BookBridge/BookBridge/Views/Review/ExchangeReview.swift

어떤 변경 사항이 있나요?
- 알람 평가기능 두개이상 평가시 하나 이외에 오작동
<br/>
<br/>

fix: 알람 평가기능 오류 수정

---

BookBridge/BookBridge/Utility/Manager/Login/NaverAuthManager.swift

어떤 변경 사항이 있나요?
- [Fix]: Naver 회원가입 버그 수정
<br/>

fix : Naver 회원가입 버그 수정

---

BookBridge/BookBridge.xcodeproj/project.pbxproj
BookBridge/BookBridge/Views/MyPage/SettingView.swift

어떤 변경 사항이 있나요?
앱스토어에 배포된 1.0.2 버전을 develop 브런치에 Merge하려고 합니다.
1. 홈에서 드래그하여 구해요, 바꿔요 탭을 변경할 수 있습니다.
2. 게시글 작성, 게시글 수정 색상을 통일했습니다.
3. 게시글 스크롤 시 아이콘 색상을 수정했습니다.
4. 게시글 신고하기 유의사항을 추가했습니다.
5. 네이버 회원가입이 안되는 버그를 수정했습니다.
<br/>
[PJ3T6_BookBridge #297]

Chore(297) 버전 1.0.2 - 책다리 to develop

---

BookBridge/BookBridge.xcodeproj/project.pbxproj
BookBridge/BookBridge/UIElement/PressGesture.swift
BookBridge/BookBridge/Views/Alert/ToastMessageView.swift
BookBridge/BookBridge/Views/Chat/ChatBottomBarView.swift
BookBridge/BookBridge/Views/Chat/MessageItemView.swift
BookBridge/BookBridge/Views/Chat/MessageListView.swift
BookBridge/BookBridge/Views/Chat/SelectMessageItemView.swift

어떤 변경 사항이 있나요?
-> 채팅 입력 TextEditor 누를때마다 키보드가 나왔다 사라지는 현상이 있었는데, 채팅내역 View를 클릭해야 키보드가 사라지게 수정
-> 클릭할 수 있는 영역 확대
-> 클릭할 수 있는 영역 확대
-> 새로운 채팅이 없어도 채팅방 입장시 최하단 메세지가 보이게 수정
<br/>
-> 채팅 입력 TextEditor 누를때마다 키보드가 나왔다 사라지는 현상이 있었는데, 채팅내역 View를 클릭해야 키보드가 사라지게 수정
|수정 전| 수정 후|
|:--:|:--:|
|<img src="https://github.com/APP-iOS3rd/PJ3T6_BookBridge/assets/112596655/91f9ef78-7151-4630-8e5a-dcc2eb35cb47" width="300">|<img src="https://github.com/APP-iOS3rd/PJ3T6_BookBridge/assets/112596655/8fb6cc0b-65a4-4674-990d-58b93112744a" width="300">|
<br/>
-> 클릭할 수 있는 영역 확대
|수정 전| 수정 후|
|:--:|:--:|
|<img src="https://github.com/APP-iOS3rd/PJ3T6_BookBridge/assets/112596655/d4f2dce9-ffba-4866-adc8-3b6d97adb020" width="300">|<img src="https://github.com/APP-iOS3rd/PJ3T6_BookBridge/assets/112596655/416dfae6-ce77-4550-9 …

Fix(300),Feat(302) 채팅방 UX 개선 및 채팅 복사하기 기능추가

---

BookBridge/BookBridge/ViewModel/NotificationViewModel.swift
BookBridge/BookBridge/ViewModel/ReviewScoreViewModel.swift
BookBridge/BookBridge/Views/HomeTap/NotificationItemView.swift
BookBridge/BookBridge/Views/MyPage/ReviewScoreView.swift

어떤 변경 사항이 있나요?
<br/>
<br/>
- [PJ3T6_BookBridge #303 ]
<br/>

fix(303) : 알림벨 기능 수정
